version: '3.8'

services:
  # Go application service
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=keerthys_trends
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # MariaDB service
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keerthys_trends
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Redis service
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  db_data: